name: AI_Chat_Factory
on:
  workflow_dispatch:
    inputs:
      chat_command:
        description: '영상의 내용을 입력하세요'
        required: true
        default: '안녕하세요 수리공님'

jobs:
  run-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install moviepy==1.0.3 requests edge-tts Pillow

      - name: Create Video
        run: |
          python auto_promo_factory.py "${{ github.event.inputs.chat_command }}"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ai-video-result
          path: ai_result.mp4
