name: Build_4K_Shorts
on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Libraries
        run: |
          pip install requests Pillow edge-tts moviepy==1.0.3

      - name: Run Factory
        run: python auto_promo_factory.py

      - name: Upload Video Result
        uses: actions/upload-artifact@v3
        with:
          name: my-video
          path: shorts_promo.mp4
